- 03:29:40.434 INFO: Input file = /home/adaddi/scratch/muscle_resampling/brd4_uniref_env_unpaired.a3m

- 03:29:40.434 INFO: Output file = /home/adaddi/scratch/muscle_resampling/c_crbn_uniref_env_hhfilter_cov30_start.a3m

- 03:29:41.395 INFO: Input file = /home/adaddi/scratch/muscle_resampling/brd4_uniref_env_unpaired.a3m

- 03:29:41.395 INFO: Output file = /home/adaddi/scratch/muscle_resampling/c_crbn_uniref_env_hhfilter_cov60_start.a3m

- 03:29:42.203 INFO: Input file = /home/adaddi/scratch/muscle_resampling/brd4_uniref_env_unpaired.a3m

- 03:29:42.203 INFO: Output file = /home/adaddi/scratch/muscle_resampling/c_crbn_uniref_env_hhfilter_cov90_start.a3m

Traceback (most recent call last):
  File "/home/adaddi/data/muscle5/muscle_MSA.py", line 120, in <module>
    muscle_foldr = resample_muscle(output_dir, hhfilter_ofile, args.mode)
  File "/home/adaddi/data/muscle5/muscle_MSA.py", line 91, in resample_muscle
    header, seqs = process_dataframe_muscle(header, seqs)
  File "/home/adaddi/data/muscle5/muscle_MSA.py", line 63, in process_dataframe_muscle
    sequence_length, n_sequnce_former = len(df.sequence.iloc[0]), len(df)
  File "/home/adaddi/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/adaddi/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/adaddi/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
